### ISSUE TITLE
Design prototype

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/lock-app#15]
Found a really cool tool for prototyping called [Figma.](https://www.figma.com)

Made the basic view for account's current locks and withdraw panel.

I'm not totally convinced with the withdraw panel view though.
Would love some suggestions.

![lock-app-prototype](https://user-images.githubusercontent.com/22663232/61552457-471fe180-aa2e-11e9-896b-7d44981387d9.png)

![lock-app proto panel](https://user-images.githubusercontent.com/22663232/61554344-17270d00-aa33-11e9-9b98-b47509ad3866.png)

**Comment by burrrata** [comment]
This is awesome. I really like the countdown timers for the locks. 

Thoughts/Questions on the withdraw view (2nd picture):
- what's the grey rectangle under the title (Withdraw Tokens) for?
- maybe change the text under the grey rectangle to "You have 2 locks ready to be withdrawn"?
- in the Withdraw box where the user specifies the amount to withdraw, is there a way to specify which lock they wish to withdraw or does it not matter?
- I like the warning that prevents the user from experiencing a snafu 👍

**Comment by fabriziovigevani** [comment]
Thanks @burrrata !

> what's the grey rectangle under the title (Withdraw Tokens) for?

That would be the action description that every panel has. If you look in redemptions for example you will see one.

> maybe change the text under the grey rectangle to "You have 2 locks ready to be withdrawn"?

 yes, makes more sense.

> in the Withdraw box where the user specifies the amount to withdraw, is there a way to specify which lock they wish to withdraw or does it not matter?

I think it doesn't matter as the user will be withdrawing  the `_numberWithdrawLocks` oldest locks. 
In practice i don't see a good reason why a user would care what locks is withdrawing.

**Comment by fabriziovigevani** [comment]
Here's the prototype using figma files provided by paty. Had to do some modifications.
For the side panel i will ask her for some samples.

![lock-app-prototype](https://user-images.githubusercontent.com/22663232/61585696-d3b6c680-ab38-11e9-8c07-209680d78020.png)

**Comment by fabriziovigevani** [comment]
closed by #31
