### ISSUE TITLE
Estimate Time

### ISSUE THREAD

**Issue by lkngtn** [1Hive/lock-app#3]

**Comment by lkngtn** [comment]
I've documented the initial requirements to allow us to have a discussion on scope and time. See #2 for more information.

**Comment by 0xGabi** [comment]
With @rperez89, @fabriziovigevani and me. We estimate:

Write Smart Contracts: **25hs**
Write Smart Contracts Test: **10hs**
Front-end: **70hs**

We also wonder why there is no `lock_amount` parameter. We not fully understand how the amount of each deposit is decided.

**Comment by lkngtn** [comment]
>  We also wonder why there is no lock_amount parameter. We not fully understand how the amount of each deposit is decided. 

This is dumb oversight on my part, thanks for pointing out!  we absolutely do need lock amount and token parameters. I will add to the readme now.
