### ISSUE TITLE
Rename "Griefing" Parameters

### ISSUE THREAD

**Issue by burrrata** [1Hive/lock-app#39]
Read through the `lock-app` multiple times, over multiple days, and didn't get it. I felt super confused because everything looked like it should make sense, but it didn't. Then I read through the PRs and closed Issues. Ah! Griefing = the parameters inside the contract that result in the `lockDuration` for the tokens. There's griefingFactor, griefingAmount, griefDuration, etc... but they all are used to calculate how long tokens should be locked up for. 

This is confusing because [Numerai](https://numer.ai/) recently just launched [Erasure](https://erasure.xxx/) and they also have a "[griefing](https://docs.erasure.xxx/erasure-quant-docs/erasure-quant-overview#griefing)" mechanism (although their definition more closely aligns with the common dictionary def). In Erasure users can stake tokens to a blinded message representing market predictions. Then hedge funds can buy that data. If the data sucks, the hedge funds can burn the seller's stake. Burning someone else's stake costs money, and the "griefing factor" is the amount of tokens the burner has to burn to burn those of the burnee (1/1, 1/5, 1/10, etc...). 

This is doubly confusing becaues the definition of griefing is to cause harm or damange and has a negative connotation ("grief"), but in the lock-app it's really just used to calculate how long a token should be locked for after a user submits a proposal. 

I'd like to suggest that we find an alternative name for the "griefing" parameters. My first choice would be "lockup"   
- griefingFact => lockupFactor
- griefAmount => lockupAmount
- griefDuration => lockupDuration
- getGriefing() => getLockup()

There's probably other/better names too and/or I might be missing something with the original thinking behind the "greifing" params, so what do you guys think?

**Comment by fabriziovigevani** [comment]
Personally i think the namings are correct.

The griefing calculation made is not exactly how many tokens should it lock and for how much time but rather the amount and duration to add to the base `lockAmount` and `lockDuration` as a penalty for having x amount of active locks, and the `griefingFactor` is a % of the initial values. 

So when an account wants to submit a proposal, will have to lock `lockAmount + (lockAmount * totalActiveLocks * (griefingFactor/ 100))` for a duration of `lockDuration + (lockDuration * totalActiveLocks * griefingFactor/ 100)`

e.g. if the `lockAmount` = 20 tokens, `lockDuration` = 6 days and `griefingFactor` is 50% and account submitting a proposal has 2 active locks, will have to lock 40 tokens for 12 days.

The idea behind it is to prevent spamming of proposals and have the members submit them thoroughly . I think this is aligned to the definition you gave for griefing as it causes some sort of damage. 

Adding  an explanation for the griefing mechanism to the README is a TODO from #33. I'll takle it today so it's well understood and doesn't cause any confusions.

**Comment by burrrata** [comment]
The way you explained it makes perfect sense. Having recently done a deep dive on the Erasure protocol, it was very very confusing to have the same term used to refer to different things. If we can avoid using the same word to describe functionality in our protocol that also refers to different functionality in a different protocol, I think that would be ideal.

**Comment by pythonpete32** [comment]
> I'd like to suggest that we find an alternative name for the "griefing" parameters. 


I haven't got around to studying the lock app yet but I agree with burrrata. The term is not intuitive but from the explanation, I do understand what it is and the point. Just think it could be simpler

**Comment by burrrata** [comment]
@fabriziovigevani incorporated your griefing explanation into the `technical-docs.md` of the `docs` branch
https://github.com/1Hive/lock-app/pull/42

**Comment by fabriziovigevani** [comment]
Okay fair enough, we could change it maybe to `penaltyAmount` and `penaltyDuration` or something around that?

**Comment by rperez89** [comment]
We are going to talk with more people about this and have some feedback

**Comment by lkngtn** [comment]
What about something like `spamPenalty` or `spamPenaltyAmount`/ `spamPenaltyDuration`
