### ISSUE TITLE
WHOLE_GRIEFING is not initialized

### ISSUE THREAD

**Issue by burrrata** [1Hive/lock-app#44]
Reading through the Aragon docs and came across the initialization section. It seems to say that global variables in apps must be initialized within the `initialize()` function, but if they are simply initialized globally they will be discarded.
- https://hack.aragon.org/docs/aragonos-building#global-variables-in-apps

On line 32 of `Lock.sol` we set `WHOLE_GRIEFING` to `100`, but do not initialize it in the `initialize()` function.
- https://github.com/1Hive/lock-app/blob/master/contracts/Lock.sol#L32
- https://github.com/1Hive/lock-app/blob/master/contracts/Lock.sol#L51

Do we need to initialize `WHOLE_GRIEFING` in the `initialize()` function along with the other global variables? 
Or is this irrelevant because `WHOLE_GRIEFING` is a `private constant`?

**Comment by fabriziovigevani** [comment]
It's the later, but the only relevant thing is the value being a `constant`. If you see in the contract every constant value is set right away. 

You can see an example in Aragon voting app [here](https://github.com/aragon/aragon-apps/blob/67e397d99e40cf75e26291c7c7e101949d54a1d6/apps/voting/contracts/Voting.sol#L24) also

**Comment by burrrata** [comment]
Awesome. Thanks for explaining that
